#pragma once

#include <QRegularExpression>
#include <QString>

// Dicionário de verbos de fala/ação e marcadores de 1ª pessoa em PT-BR,
// portado de dialogVerbs.js (Mira 1). DialogueDetector usa isso pra
// atribuição de falas por proximidade (verbo perto do nome do personagem) e
// pra detectar narração em 1ª pessoa quando há um personagem marcado como
// Narrador.
namespace DialogueVerbs {

// Fonte da alternação regex (sem \b nem grupo externo) — mesmo formato de
// DIALOG_SPEECH_VERBS_SRC no original, pra poder ser embutida em regexes
// maiores (proximidade com o nome do personagem).
inline const QString& speechVerbsSource()
{
    static const QString src = QStringLiteral(
        // Fala direta
        "disse|diz|dizendo|"
        "falou|fala|falando|"
        "respondeu|responde|respondendo|"
        "perguntou|pergunta|perguntando|"
        "gritou|grita|gritando|"
        "berrou|berra|berrando|"
        "sussurrou|sussurra|sussurrando|"
        "murmurou|murmura|murmurando|"
        "cochichou|cochicha|cochichando|"
        "segredou|segredando|"
        "exclamou|exclama|exclamando|"
        "bradou|brada|bradando|"
        "vociferou|vocifera|vociferando|"
        "clamou|clama|clamando|"
        "rugiu|ruge|rugindo|"
        "rosnou|rosna|rosnando|"
        "uivou|uiva|uivando|"
        "bufou|bufa|bufando|"
        "arfou|arfa|arfando|"
        "gemeu|geme|gemendo|"
        "soluçou|soluça|soluçando|"
        "chorou|chora|chorando|"
        "riu|ri|rindo|"
        "fungou|funga|fungando|"
        "engasgou|engasga|engasgando|"
        "pigarreou|pigarreando|"
        "tossiu|tosse|tossindo|"
        "cantou|canta|cantando|"
        "recitou|recita|recitando|"
        "suspirou|suspira|suspirando|"
        "gaguejou|gagueja|gaguejando|"
        "balbuciou|balbucia|balbuciando|"
        "bocejou|boceja|bocejando|"
        // Atribuição e resposta
        "comentou|comenta|comentando|"
        "observou|observa|observando|"
        "notou|nota|notando|"
        "continuou|continua|continuando|"
        "acrescentou|acrescenta|acrescentando|"
        "interrompeu|interrompe|interrompendo|"
        "interveio|intervém|intervindo|"
        "retrucou|retrucando|"
        "retorquiu|retorquindo|"
        "insistiu|insiste|insistindo|"
        "repetiu|repete|repetindo|"
        "hesitou|hesita|hesitando|"
        "concordou|concorda|concordando|"
        "discordou|discorda|discordando|"
        "assentiu|assente|assentindo|"
        "reclamou|reclama|reclamando|"
        "queixou|queixa|queixando|"
        "resmungou|resmungo|resmungando|"
        "lamentou|lamenta|lamentando|"
        "protestou|protesta|protestando|"
        "brincou|brinca|brincando|"
        "ironizou|ironiza|ironizando|"
        "gozou|goza|gozando|"
        // Revelação e declaração
        "confessou|confessa|confessando|"
        "admitiu|admite|admitindo|"
        "revelou|revela|revelando|"
        "declarou|declara|declarando|"
        "afirmou|afirma|afirmando|"
        "negou|nega|negando|"
        "confirmou|confirma|confirmando|"
        "informou|informa|informando|"
        "explicou|explica|explicando|"
        "contou|conta|contando|"
        "narrou|narra|narrando|"
        "anunciou|anuncia|anunciando|"
        "mentiu|mente|mentindo|"
        "prometeu|promete|prometendo|"
        "jurou|jura|jurando|"
        // Pedido e comando
        "chamou|chama|chamando|"
        "pediu|pede|pedindo|"
        "ordenou|ordena|ordenando|"
        "exigiu|exige|exigindo|"
        "suplicou|suplica|suplicando|"
        "implorou|implora|implorando|"
        "advertiu|adverte|advertindo|"
        "alertou|alerta|alertando|"
        "ameaçou|ameaça|ameaçando|"
        // Sugestão e persuasão
        "sugeriu|sugere|sugerindo|"
        "propôs|propôe|propondo|"
        "persuadiu|persuade|persuadindo|"
        "convenceu|convence|convencendo|"
        "capitulou|capitula|capitulando|"
        "cedeu|cede|cedendo|"
        // Expressão corporal e ação (comuns na atribuição de diálogo)
        "sorriu|sorri|sorrindo|"
        "franziu|franze|franzindo|"
        "arqueou|arqueia|arqueando|"
        "piscou|pisca|piscando|"
        "acenou|acena|acenando|"
        "gesticulou|gesticula|gesticulando|"
        "apontou|aponta|apontando|"
        "encarou|encara|encarando|"
        "fitou|fita|fitando|"
        "olhou|olha|olhando|"
        "virou|vira|virando|"
        "ergueu|ergue|erguendo|"
        "abaixou|abaixa|abaixando|"
        "inclinou|inclina|inclinando|"
        "curvou|curva|curvando|"
        "recuou|recua|recuando|"
        "avançou|avança|avançando|"
        "aproximou|aproxima|aproximando|"
        "afastou|afasta|afastando|"
        "levantou|levanta|levantando|"
        "sentou|senta|sentando|"
        "agachou|agacha|agachando|"
        "ajoelhou|ajoelha|ajoelhando|"
        "deitou|deita|deitando|"
        "debruçou|debruça|debruçando|"
        "encostou|encosta|encostando|"
        "andou|anda|andando|"
        "parou|para|parando|"
        "correu|corre|correndo|"
        "entrou|entra|entrando|"
        "saiu|sai|saindo|"
        "chegou|chega|chegando|"
        "voltou|volta|voltando|"
        "cruzou|cruza|cruzando|"
        "balançou|balança|balançando|"
        "sacudiu|sacode|sacudindo|"
        "chacoalhou|chacoalha|chacoalhando|"
        "tremeu|treme|tremendo|"
        "estremeceu|estremece|estremecendo|"
        "respirou|respira|respirando|"
        "encolheu|encolhe|encolhendo|"
        "puxou|puxa|puxando|"
        "empurrou|empurra|empurrando|"
        "apertou|aperta|apertando|"
        "soltou|solta|soltando|"
        "segurou|segura|segurando|"
        "atirou|atira|atirando|"
        "lançou|lança|lançando|"
        "jogou|joga|jogando|"
        "largou|larga|largando|"
        "tocou|toca|tocando|"
        "bateu|bate|batendo|"
        "abriu|abre|abrindo|"
        "fechou|fecha|fechando|"
        "mordeu|morde|mordendo|"
        "engoliu|engole|engolindo|"
        "abraçou|abraça|abraçando|"
        "beijou|beija|beijando|"
        "cutucou|cutuca|cutucando|"
        "beliscou|belisca|beliscando|"
        "esfregou|esfrega|esfregando|"
        "limpou|limpa|limpando|"
        "acariciou|acaricia|acariciando|"
        "coçou|coça|coçando|"
        "dobrou|dobra|dobrando|"
        "espreitou|espreita|espreitando|"
        "espreguiçou|espreguiça|espreguiçando|"
        "corou|cora|corando|"
        "enrijeceu|enrijece|enrijecendo|"
        "relaxou|relaxa|relaxando|"
        // Ação física — combate e contato
        "chutou|chuta|chutando|"
        "socou|soca|socando|"
        "esmurrou|esmurra|esmurrando|"
        "esbofeteou|esbofeteia|esbofeteando|"
        "arranhou|arranha|arranhando|"
        "desferiu|desfere|desferindo|"
        "cerrou|cerra|cerrando|"
        "agarrou|agarra|agarrando|"
        "pegou|pega|pegando|"
        "deixou|deixa|deixando|"
        "colocou|coloca|colocando|"
        "tirou|tira|tirando|"
        "trouxe|traz|trazendo|"
        "esticou|estica|esticando|"
        "torceu|torce|torcendo|"
        "abanou|abana|abanando|"
        "lambeu|lambe|lambendo|"
        // Movimento e deslocamento
        "pulou|pula|pulando|"
        "saltou|salta|saltando|"
        "caiu|cai|caindo|"
        "tropeçou|tropeça|tropeçando|"
        "escorregou|escorrega|escorregando|"
        "deslizou|desliza|deslizando|"
        "rastejou|rasteja|rastejando|"
        "arrastou|arrasta|arrastando|"
        "girou|gira|girando|"
        "rodou|roda|rodando|"
        "fugiu|foge|fugindo|"
        "escapou|escapa|escapando|"
        "sumiu|some|sumindo|"
        "surgiu|surge|surgindo|"
        "apareceu|aparece|aparecendo|"
        "atravessou|atravessa|atravessando|"
        "caminhou|caminha|caminhando|"
        "marchou|marcha|marchando|"
        "subiu|sobe|subindo|"
        "desceu|desce|descendo|"
        "recostou|recosta|recostando|"
        "endireitou|endireita|endireitando|"
        "semicerrou|semicerra|semicerrando|"
        // Respiração e reações físicas
        "ofegou|ofega|ofegando|"
        "inspirou|inspira|inspirando|"
        "expirou|expira|expirando|"
        "espirrou|espirra|espirando|"
        "gargalhou|gargalha|gargalhando|"
        "empalideceu|empalidece|empalidecendo|"
        "arrepiou|arrepia|arrepiando|"
        "gelou|gela|gelando|"
        // Alimentação e consumo
        "bebeu|bebe|bebendo|"
        "comeu|come|comendo|"
        "fumou|fuma|fumando|"
        "mastigou|mastiga|mastigando|"
        "serviu|serve|servindo|"
        // Mental e percepção
        "pensou|pensa|pensando|"
        "lembrou|lembra|lembrando|"
        "percebeu|percebe|percebendo|"
        "imaginou|imagina|imaginando|"
        "tentou|tenta|tentando|"
        "decidiu|decide|decidindo|"
        "duvidou|duvida|duvidando|"
        "acreditou|acredita|acreditando|"
        "esperou|espera|esperando|"
        "descobriu|descobre|descobrindo|"
        // Imperfeito (-ava / -ia) — ações contínuas/descritivas em cena de diálogo
        "dizia|falava|respondia|perguntava|gritava|berrava|"
        "sussurrava|murmurava|cochichava|exclamava|bradava|vociferava|"
        "clamava|gemendo|gemia|soluçava|chorava|ria|fungava|"
        "engasgava|tossia|cantava|recitava|suspirava|gaguejava|"
        "balbuciava|bocejava|arfava|rugia|rosnava|uivava|bufava|"
        "comentava|observava|notava|continuava|acrescentava|"
        "interrompia|insistia|repetia|hesitava|concordava|discordava|"
        "reclamava|queixava|resmungava|lamentava|protestava|"
        "brincava|ironizava|gozava|retrucava|"
        "confessava|admitia|revelava|declarava|afirmava|negava|"
        "confirmava|informava|explicava|contava|narrava|anunciava|"
        "mentia|prometia|jurava|"
        "chamava|pedia|ordenava|exigia|suplicava|implorava|"
        "advertia|alertava|ameaçava|sugeria|persuadia|convencia|"
        "sorrindo|franzia|arqueava|piscava|acenava|gesticulava|"
        "apontava|encara|fitava|olhava|virava|erguia|"
        "abaixava|inclinava|curvava|recuava|avançava|aproximava|"
        "afastava|levantava|sentava|agachava|ajoelhava|deitava|"
        "debruçava|encostava|andava|parava|corria|entrava|"
        "saía|chegava|voltava|cruzava|balançava|sacudia|"
        "chacoalhava|tremia|estremecia|respirava|encolhia|"
        "puxava|empurrava|apertava|soltava|segurava|atirava|"
        "lançava|jogava|largava|tocava|batia|abria|fechava|"
        "mordia|engolia|abraçava|beijava|cutucava|beliscava|"
        "esfregava|limpava|acariciava|coçava|dobrava|espreitava|"
        "relaxava|corava|enrijecendo|"
        "chutava|socava|esmurrava|esbofeteava|arranhava|desfiria|"
        "cerrava|agarrava|pegava|deixava|colocava|tirava|trazia|"
        "esticava|torcia|abanava|lambia|"
        "pulava|saltava|caía|tropeçava|escorregava|deslizava|"
        "rastejava|arrastava|girava|rodava|fugia|escapava|"
        "sumia|surgia|aparecia|atravessava|caminhava|marchava|"
        "subia|descia|recostava|endireitava|semicerrava|"
        "ofegava|inspirava|expirava|espirava|gargalhava|"
        "empalidecia|arrepiava|gelava|"
        "bebia|comia|fumava|mastigava|servia|"
        "pensava|lembrava|percebia|imaginava|tentava|"
        "decidia|duvidava|acreditava|esperava|descobria"
    );
    return src;
}

// \b(...)\b — regex pronta pra checar se um trecho contém algum verbo de
// fala/ação do dicionário (usado no "hasSpeechVerb" antes de guardar a
// linha como candidata a diálogo).
inline const QRegularExpression& speechVerbsRegex()
{
    static const QRegularExpression re(
        QStringLiteral("\\b(%1)\\b").arg(speechVerbsSource()),
        QRegularExpression::CaseInsensitiveOption);
    return re;
}

// Verbos/marcadores exclusivos da 1ª pessoa do singular — usados pra
// detectar diálogo do narrador quando ele conta a história em 1ª pessoa.
// Só formas que NÃO colidem com a 3ª pessoa (portado de FIRST_PERSON no
// dialogVerbs.js original).
inline const QString& firstPersonVerbsSource()
{
    static const QString src = QStringLiteral(
        "falei|gritei|berrei|murmurei|sussurrei|cochichei|exclamei|"
        "bradei|clamei|chorei|funguei|cantei|recitei|suspirei|"
        "gaguejei|balbuciei|bocejei|arfei|mirei|"
        "comentei|observei|notei|continuei|acrescentei|retrucuei|"
        "insisti|repeti|hesitei|concordei|discordei|reclamei|"
        "resmunguei|lamentei|protestei|brinquei|ironizei|"
        "confessei|revelei|declarei|afirmei|neguei|confirmei|"
        "informei|expliquei|contei|narrei|anunciei|prometi|jurei|"
        "chamei|pedi|ordenei|exigi|supliquei|implorei|adverti|"
        "alertei|ameacei|sugeri|convenci|capitulei|cedi|"
        "sorri|olhei|virei|ergui|abaixei|inclinei|curvei|"
        "recuei|avancei|aproximei|afastei|levantei|sentei|"
        "agachei|ajoelhei|deitei|debrucei|encostei|andei|parei|"
        "entrei|cruzei|balancei|sacudi|chacoalhei|tremi|estremeci|"
        "respirei|encolhi|puxei|empurrei|apertei|soltei|segurei|"
        "atirei|lancei|joguei|larguei|toquei|bati|abri|fechei|"
        "mordi|engoli|abracei|beijei|cutucuei|belisquei|esfregei|"
        "limpei|acariciei|cocei|dobrei|espreitei|relaxei|corei|"
        "chutei|soquei|esmurrei|arranhei|cerrei|agarrei|peguei|"
        "deixei|coloquei|tirei|esticei|torci|abanei|lambi|"
        "pulei|saltei|caí|tropecei|escorregei|deslizei|rastejei|"
        "arrastei|girei|rodei|fugi|escapei|sumi|surgi|apareci|"
        "atravessei|caminhei|marchei|subi|desci|recostei|"
        "endireitei|semicerrei|ofeguei|inspirei|expirei|espirrei|"
        "gargalhei|empalideci|arrepiei|gelei|"
        "bebi|comi|fumei|mastiguei|servi|"
        "pensei|lembrei|percebi|imaginei|tentei|decidi|"
        "duvidei|acreditei|esperei|descobri|"
        "voltei|cheguei|saí|pisquei|acenei|gesticulei|apontei|"
        "encarei|fitei|franzei|arqueei|pigarreei|"
        "enrijecei|espreguicei|recarreguei|amassei|vacilei|"
        "fiquei|comecei|precisei|tomei|passei|encontrei|trabalhei|"
        "amei|ganhei|paguei|usei|ajudei|mudei|guardei|gostei|"
        "morei|comprei|levei|mostrei|acordei|terminei|acabei|"
        "cortei|tratei|criei|preparei|procurei|estudei|escutei|"
        "dancei|busquei|namorei|rezei|liguei|"
        "demorei|juntei|misturei|separei|organizei|"
        "senti|ouvi|vivi|escrevi|entendi|conheci|sofri|aprendi|"
        "consegui|dormi|corri|parti|perdi|recebi|segui|vendi|"
        "vesti|dirigi|fingi|desisti|assisti|resisti|preferi|"
        "escolhi|produzi|conduzi|reduzi|cresci|movi|resolvi|"
        "envolvi|devolvi|construí|atraí|distraí|li|menti|"
        "cobri|"
        "fiz|fui|vim|pude|vi|tive|estive|"
        "quis|pus|disse|"
        "estou|tenho|vejo|faço|vou|sei|posso|quero|digo|"
        "venho|ponho|trago|ouço|valho|caibo|"
        "sinto|fico|começo|preciso|tomo|passo|encontro|"
        "trabalho|amo|ganho|pago|uso|ajudo|mudo|guardo|"
        "gosto|moro|compro|levo|mostro|acordo|termino|acabo|"
        "corto|trato|crio|preparo|procuro|estudo|escuto|danço|"
        "corro|durmo|parto|perco|visto|dirijo|escrevo|leio|"
        "vivo|entendo|conheço|sofro|aprendo|finjo|desisto|"
        "consigo|prefiro|resolvo|envolvo|produzo|construo|"
        "atraio|sigo|recebo|vendo|"
        "falo|grito|berro|murmuro|cochicho|exclamo|brado|gemo|"
        "soluco|choro|canto|recito|suspiro|gaguejo|balbucio|"
        "boceio|comento|observo|noto|continuo|acrescento|"
        "insisto|repito|hesito|concordo|discordo|reclamo|"
        "resmungo|lamento|protesto|brinco|ironizo|"
        "confesso|admito|revelo|declaro|afirmo|nego|confirmo|"
        "informo|explico|conto|narro|anuncio|minto|prometo|juro|"
        "chamo|peço|ordeno|exijo|suplico|imploro|adverto|"
        "alerto|ameaco|sugiro|convenco|cedo|sorrio|"
        "olho|viro|ergo|abaixo|inclino|curvo|recuo|avanco|"
        "aproximo|afasto|levanto|sento|agacho|ajoelho|deito|"
        "debruco|encosto|ando|paro|entro|cruzo|balanco|sacudo|"
        "chacoalho|tremo|estremeço|respiro|encolho|puxo|empurro|"
        "aperto|solto|seguro|atiro|lanco|jogo|largo|toco|"
        "bato|abro|fecho|mordo|engulo|abraco|beijo|cutuco|"
        "belisco|limpo|acaricio|dobro|espreito|"
        "relaxo|coro|chuto|soco|esmurro|cerro|agarro|"
        "pego|deixo|coloco|tiro|estico|torco|abano|lambo|"
        "pulo|salto|tropeço|escorrego|deslizo|rastejo|arrasto|"
        "giro|rodo|fujo|escapo|sumo|surjo|apareço|atravesso|"
        "caminho|marcho|subo|desço|recosto|endireito|"
        "inspiro|expiro|espirro|gargalho|"
        "arrepio|gelo|bebo|como|fumo|mastigo|sirvo|"
        "penso|lembro|percebo|imagino|tento|decido|"
        "duvido|acredito|espero|descubro|"
        "volto|chego|saio|pisco|aceno|gesticulo|aponto|"
        "encaro|fito|franzo|arqueio|"
        "farei|irei|direi|serei|terei|virei|verei|estarei|"
        "poderei|quererei|saberei|porei|trarei|"
        "falarei|sentirei|ouvirei|escreverei|entenderei|"
        "conhecerei|conseguirei|dormirei|correrei|partirei|perderei|"
        "receberei|venderei|ficarei|começarei|precisarei|tomarei|"
        "passarei|encontrarei|trabalharei|amarei|ganharei|pagarei|"
        "usarei|ajudarei|mudarei|gostarei|morarei|comprarei|"
        "levarei|mostrarei|acordarei|terminarei|acabarei|tratarei|"
        "criarei|prepararei|procurarei|estudarei|escutarei|"
        "pensarei|lembrarei|tentarei|esperarei|voltarei|chegarei|"
        "pararei|entrarei|jogarei|pegarei|deixarei|"
        "colocarei|tirarei|pularei|subirei|correrei|"
        "escolherei|sofrerei|aprenderei|crescerei|assistirei|"
        "resistirei|desistirei|preferirei|seguirei|vestirei"
    );
    return src;
}

// \b(eu|me\s+\w|verbos exclusivos de 1ª pessoa|possessivos)\b — mesma
// composição do FIRST_PERSON_MARKERS original.
inline const QRegularExpression& firstPersonMarkersRegex()
{
    static const QRegularExpression re(
        QStringLiteral("\\b(eu|me\\s+\\w|meu|minha|meus|minhas|comigo|%1)\\b")
            .arg(firstPersonVerbsSource()),
        QRegularExpression::CaseInsensitiveOption);
    return re;
}

} // namespace DialogueVerbs
