#pragma once
// Tipos e utilitários de desenho compartilhados pela Timeline nova (Trilhos,
// Trança e o painel lateral). Os dados chegam prontos do TimelinePanel — as
// views só desenham e devolvem intenções por sinal, nunca mexem no modelo.

#include <QColor>
#include <QFont>
#include <QFontMetricsF>
#include <QImage>
#include <QList>
#include <QPainter>
#include <QPainterPath>
#include <QString>
#include <QStringList>

namespace Tracks {

// Uma coluna = uma unidade de leitura (capítulo sem cenas, ou uma cena).
struct Column {
    QString key;             // "chapterId:sceneIndex" (0 = capítulo sem cenas)
    QString chapterId;
    int     sceneIndex = -1; // -1 = capítulo inteiro
    QString manuscriptId;
    QString ruler;           // rótulo curto da régua: "5", "5·2", "Pról."
    QString unitLabel;       // "Capítulo 5" / "Capítulo 5 · Cena 2" (painel)
};

struct Lane {
    QString id;
    QString name;
    QString kind;            // TimelineKind::*
    QString sub;             // linha pequena sob o nome ("automática")
    QString tip;             // tooltip com a origem completa
    QString parentId;        // ramificação: linha de onde nasceu
    QColor  color;
    bool    dashed = false;
    bool    autoGenerated = false;
};

struct Event {
    QString id;
    QString laneId;          // linha efetiva
    int     col = -1;        // índice em Data::cols; -1 = Soltos
    int     order = 0;       // ordem dentro da coluna (eventos manuais)
    bool    manual = false;  // criado à mão (não vem de capítulo/cena)
    bool    hollow = false;  // capítulo/cena sem marcador de tempo
    bool    moved = false;   // linha escolhida pelo usuário, diferente da automática
    QString autoLaneId;      // linha que a detecção escolheria (pro "Desfazer")
    QString title;
    QString marker;
    QString summary;
    QStringList castIds;     // Element::id dos personagens presentes
    QString placeId;
    QString placeName;
    QString origin;          // editor | timeline | lousa | new | "" (manual antigo)
    QString originWhere;     // "Cap 5, parágrafo 14"
    QString originShort;     // "Lousa", "+ Evento", "Editor", "Timeline" (cartão solto)
    qreal   chrono = 0.0;    // TimelineChrono::parse (minutos)
    bool    chronoOk = false;
};

struct Character {
    QString id;
    QString name;
    QColor  color;
    QImage  avatar;          // vazio = inicial
};

struct Data {
    QList<Column>    cols;
    QList<Lane>      lanes;
    QList<Event>     events;
    QList<Character> chars;
    int     editorCol = -1;  // coluna aberta no editor
    int     chapterCount = 0;
    QString manuscriptTitle;
    QString startMarker;     // data-base do manuscrito ("quando a história começa")
    qreal   startChrono = 0.0;
    bool    startOk = false;

    int laneIndex(const QString& id) const {
        for (int i = 0; i < lanes.size(); ++i) if (lanes[i].id == id) return i;
        return -1;
    }
    const Lane* lane(const QString& id) const {
        const int i = laneIndex(id); return i < 0 ? nullptr : &lanes[i];
    }
    const Event* event(const QString& id) const {
        for (const auto& e : events) if (e.id == id) return &e;
        return nullptr;
    }
    const Character* character(const QString& id) const {
        for (const auto& c : chars) if (c.id == id) return &c;
        return nullptr;
    }
};

// Estado de filtro/foco compartilhado pelas views (esmaecer, nunca esconder).
struct Filter {
    QString charId;
    QString placeId;
    QString laneId;          // foco por linha
    QString query;
    bool dims(const Event& e) const {
        if (!charId.isEmpty()  && !e.castIds.contains(charId)) return true;
        if (!placeId.isEmpty() && e.placeId != placeId) return true;
        if (!laneId.isEmpty()  && e.laneId != laneId) return true;
        if (!query.isEmpty()
            && !(e.title + QLatin1Char(' ') + e.summary).contains(query, Qt::CaseInsensitive))
            return true;
        return false;
    }
};

// Onde uma ramificação nasce e onde volta. first/last = colunas dos eventos
// da própria linha; from = última coluna da linha-mãe antes do nascimento;
// to = primeira coluna da linha-mãe depois do fim em que o elenco da
// ramificação reencontra o da mãe (convergência). -1 = não existe.
struct BranchSpan { int parent = -1; int from = -1; int first = -1; int last = -1; int to = -1; };
BranchSpan branchSpan(const Data& d, int laneIndex);

// ── Paleta derivada do tema ativo ────────────────────────────────────────────
struct Palette {
    QColor page, panel, border, ink, bright, muted, app;
    QColor accent, warning, info, success, danger;
    QColor dim;    // texto secundário (ink 64% sobre o painel)
    QColor faint;  // divisórias quase invisíveis
    static Palette current();
};

inline QColor mix(const QColor& a, const QColor& b, qreal wa)
{
    const qreal wb = 1.0 - wa;
    return QColor::fromRgbF(float(a.redF() * wa + b.redF() * wb),
                            float(a.greenF() * wa + b.greenF() * wb),
                            float(a.blueF() * wa + b.blueF() * wb),
                            float(a.alphaF() * wa + b.alphaF() * wb));
}
inline QColor alpha(QColor c, qreal a) { c.setAlphaF(float(a)); return c; }

QFont serifFont(qreal px, int weight = QFont::DemiBold, bool italic = false);
QFont monoFont(qreal px, int weight = QFont::Normal);
QFont uiFont(qreal px, int weight = QFont::Normal);

// Quebra em até maxLines linhas; a última é elidida com "…" se sobrar texto.
QStringList wrapLines(const QString& text, const QFont& font, qreal width, int maxLines);

// Texto centrado em cx com "halo" na cor do fundo — nenhuma linha passa por
// cima de letra (equivale ao text-shadow do protótipo).
void drawHaloText(QPainter* p, const QString& line, const QFont& font,
                  qreal cx, qreal baseline, const QColor& fill, const QColor& halo,
                  Qt::Alignment align = Qt::AlignHCenter);

// Bolinha padrão: anel na cor da linha + ponto no meio. hollow = só o anel
// (sem data); sel = halo; hover = ponto maior; small = evento manual (nota).
void drawKnot(QPainter* p, const QPointF& c, qreal r, const QColor& col, const QColor& bg,
              bool hollow, bool sel, bool hover, bool small);

// Intervalo em dias → "+5 dias" / "+3 meses" / "+8 anos"; vazio se ≤ 1 dia.
QString fmtGap(qreal days);
// Mesma escala, sem o "+" e aceitando 0/1 ("mesmo dia", "1 dia").
QString gapWord(qreal days);

// Avatar redondo (foto ou inicial) — mesma peça no elenco e no painel.
void drawAvatar(QPainter* p, const QRectF& r, const Character& c, const QColor& ink);

} // namespace Tracks
